apiVersion: v1
kind: Template
metadata:
  name: operator-registry
  annotations:
    description: "A template to instantiate an operator registry catalog from manifests a file/archive repo like Artifactory"
    tags: "artifactory,operators,registry,catalog"
labels:
  app: ${NAME}
parameters:
- description: "Name of Operator Catalog -- will be applied to labels on all dependent objects"
  name: NAME
  required: true
- description: "Random 4 char string to append to NAME"
  name: RANDOM
  generate: expression
  from: "[a-zA-Z0-9]{5}"
- description: "if set, logs will have debug level output from the bash script controlling the registry server"
  name: DEBUG_BASH
  required: false
- description: "The base URL of the Artifactory instance. This will be use to add '/api/*' for api calls, and to append the .tar.gz path to"
  name: ARTIFACTORY_BASE_URL
  required: true
- description: "The Path of the .tar.gz file in Artifactory. This value will be concatenated with ARTIFACTORY_BASE_URL to create the complete URL of the archive in Artifactory"
  name: ARTIFACTORY_ARTIFACT_PATH
  required: true
- description: "the Artifactory or other file/archive repo credentials, which will be passed to curl the archive, ex: -uadmin:password. Leave blank if no necessary"
  name: CURL_FETCH_CREDS
  required: false
- description: "The image tag of the operator-registry"
  name: "IMAGE"
  required: true
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      opsrc-owner-name: ${NAME}
      opsrc-owner-namespace: openshift-marketplace
    name: ${NAME}
  spec:
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      marketplace.operatorSource: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      opsrc-owner-name: ${NAME}
      opsrc-owner-namespace: openshift-marketplace
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        marketplace.operatorSource: ${NAME}
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          marketplace.operatorSource: ${NAME}
        name: ${NAME}
        namespace: openshift-marketplace
      spec:
        containers:
        - env:
          - name: HTTP_PROXY
          - name: HTTPS_PROXY
          - name: NO_PROXY
          - name: CURL_FETCH_CREDS
            value: "${CURL_FETCH_CREDS}"
          - name: ARTIFACTORY_BASE_URL
            value: "${ARTIFACTORY_BASE_URL}"
          - name: ARTIFACTORY_ARTIFACT_PATH
            value: "${ARTIFACTORY_ARTIFACT_PATH}"
          - name: DEBUG_BASH
            value: "${DEBUG_BASH}"
          image: ${IMAGE}
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - grpc_health_probe
              - -addr=localhost:50051
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${NAME}
          ports:
          - containerPort: 50051
            name: grpc
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - grpc_health_probe
              - -addr=localhost:50051
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/pki/ca-trust/extracted/pem/
            name: marketplace-trusted-ca
        dnsPolicy: ClusterFirst
        nodeSelector:
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: ca-bundle.crt
              path: tls-ca-bundle.pem
            name: marketplace-trusted-ca
          name: marketplace-trusted-ca
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    labels:
      olm-visibility: hidden
      openshift-marketplace: "true"
      opsrc-datastore: "true"
      opsrc-owner-name: ${NAME}
      opsrc-owner-namespace: openshift-marketplace
      opsrc-provider: ${NAME}
    name: ${NAME}
  spec:
    address: ${NAME}.openshift-marketplace.svc:50051
    displayName: ${NAME}
    icon:
      base64data: ""
      mediatype: ""
    publisher: publisher
    sourceType: grpc
